<a href="https://colab.research.google.com/github/G0391/HENRY/blob/main/Homework_Resuelto_CLASE_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica Clase 3

## Numpy

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [ ]:
import numpy as np
# Crear una lista Numpy
arr = np.array([1, 2, 3, 4, 5])

# Indexar el primer elemento
print(arr[0])
# Salida: 1

# Crear una lista
list = [1, 2, 3, 4, 5]

# Indexar el primer elemento
print(list[0])
# Output: 1


1
1


In [ ]:

#Indexación: Los arreglos de NumPy pueden ser indexados de forma similar a las listas, pero también pueden ser indexados usando índices booleanos. Esto permite realizar operaciones complejas como filtrar y seleccionar subconjuntos de arreglos. Por ejemplo, el siguiente código selecciona todos los elementos del arreglo c que son mayores que 5:
c[c > 5]
np.array([6, 7, 9])




array([6, 7, 9])

In [ ]:

#La diferencia entre un arreglo de forma (n,), (n,1) y (1,n) es la dimensión del arreglo. Un arreglo de forma (n,) es un arreglo unidimensional con n elementos. Un arreglo de forma (n,1) es un arreglo bidimensional con n filas y 1 columna. Un arreglo de forma (1,n) es un arreglo bidimensional con 1 fila y n columnas.

#arreglo unidimensional:

import numpy as np
a = np.array([1, 2, 3, 4, 5])
a.shape
(5,)


(5,)

In [ ]:
#arreglo bidimensional con n filas y 1 columna:
import numpy as np
b = np.array([[1], [2], [3], [4], [5]])
b.shape
(5, 1)

(5, 1)

In [ ]:
#arreglo bidimensional con 1 fila y n columnas:
import numpy as np
c = np.array([[1, 2, 3, 4, 5]])
c.shape
(1, 5)

(1, 5)

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [1]:
import numpy as np

numbers = np.arange(0, 10)
print(numbers)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
import numpy as np

numbers = np.linspace(0, 9, 100)
print(numbers)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [3]:
numbers = np.arange(10, 101)

mask = numbers % 3 == 0

divisible_by_3 = numbers[mask]

print(divisible_by_3)


[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96 99]


**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [ ]:
import numpy as np

arreglo_enteros = np.arange(10)

print(arreglo_enteros)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

# Crear un arreglo de ejemplo de 5 filas y 3 columnas
arreglo = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12],
                    [13, 14, 15]])

# Reemplazar la segunda fila y la cuarta fila con unos
arreglo[1] = 1
arreglo[3] = 1

print(arreglo)

[[ 1  2  3]
 [ 1  1  1]
 [ 7  8  9]
 [ 1  1  1]
 [13 14 15]]


In [6]:
matrix = np.array([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15]])

matrix[:, 2] = 2
matrix[:, 4] = 2

print(matrix)

[[ 1  2  2  4  2]
 [ 6  7  2  9  2]
 [11 12  2 14  2]]


**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html